openapi: "3.0.0"

paths:
  /repository/contracts/{matchType}/{chain}/{address}/{filePath}:
    get:
      deprecated: true
      summary: Get a specific file from the repository with the file path (static serving)
      description: Retrieve statically served files over the server.
      tags:
        - (Deprecated) Repository
      parameters:
        - name: matchType
          in: path
          required: true
          schema:
            type: string
            format: match-type
          description: Either `full_match` or `partial_match`
        - name: chain
          in: path
          required: true
          schema:
            type: string
            format: sourcify-chainId
        - name: address
          in: path
          required: true
          schema:
            type: string
            format: address
        - name: filePath
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The file is found at the path
          content:
            text/plain: {}
        "404":
          description: The file is not found at the path
          content:
            text/plain: {}
